# Ant parameters
AntCount: 20

# Map parameters
VertexCount: 16 # uint8_t
EdgeCount: 32 # Max: (V*(V-1)/2); Min: V-1
MaxEdgeWeight: 8 # uint8_t

# How much will ants avoid long paths? (>=1, default 1):
DistancePower: 1.
# How long will pheromones stay on the trails? (1>= and >=0, default=0)
EvaporationPower: 0.
# How much will ants trust known paths? (>=0, default=0)
PheromonePower: 0.
# How much pheromone is dropped on reaching a goal? (default: 1):
RewardPower: 1.
