# Map Parameters
GraphType: Incomplete
VertexCount: 5
MaxEdgeWeight: 2

DistancePower: 1.0 # Increase to avoid long trips.
PheromonePower: 0.5 # Increase to trust other ants.
EvaporationPower: 0.0 # Increase to remove older paths.
RewardPower: 1.0 # Increase to favor newest paths.