# Map Parameters
VertexCount: 5
size_x: 60
size_y: 60

# Algorithm Parameters
DistancePower: 1.0 # Increase to avoid long trips.
PheromonePower: 0.5 # Increase to trust other ants.
EvaporationPower: 0.0 # Increase to remove older paths.
RewardPower: 1.0 # Increase to favor newest paths.